apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::802430134075:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-GnvVGDVpCrvE
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn:arn:aws:iam::802430134075:user/ram
      username: ramya    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-06T12:39:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1325"
  uid: 025acd00-ee16-4f3c-a3ca-bb4b533cd5e0

